[package]
name = "lightning-path"
version = "1.0.0"
license = "MIT"
description = "Route Recognizer library for lightning-fast matching"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
]

[dependencies]
